// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYa_d4Yi_5BF9sYlq6DHWzz6TiILNUtko',
    appId: '1:804262501413:web:13f74748f8ca12e01fb3cc',
    messagingSenderId: '804262501413',
    projectId: 'flavorfusion-55c75',
    authDomain: 'flavorfusion-55c75.firebaseapp.com',
    storageBucket: 'flavorfusion-55c75.firebasestorage.app',
    measurementId: 'G-JJE3WKGE9V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQJdF2SQI7MFUP2nVjWHRt7ZqKnrNSQtI',
    appId: '1:804262501413:android:8b6101514f8048701fb3cc',
    messagingSenderId: '804262501413',
    projectId: 'flavorfusion-55c75',
    storageBucket: 'flavorfusion-55c75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB5L2JEsAqoehqnHvlDuXVUQ5IRQwDWS4',
    appId: '1:804262501413:ios:9dd81d958b6532e31fb3cc',
    messagingSenderId: '804262501413',
    projectId: 'flavorfusion-55c75',
    storageBucket: 'flavorfusion-55c75.firebasestorage.app',
    androidClientId: '804262501413-pnhi34kohvjln9ikpb0bri6s0mrbqdeb.apps.googleusercontent.com',
    iosClientId: '804262501413-srrmjs2ua5kl0c1ljbe2admm9u2ja8b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavorfusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB5L2JEsAqoehqnHvlDuXVUQ5IRQwDWS4',
    appId: '1:804262501413:ios:9dd81d958b6532e31fb3cc',
    messagingSenderId: '804262501413',
    projectId: 'flavorfusion-55c75',
    storageBucket: 'flavorfusion-55c75.firebasestorage.app',
    androidClientId: '804262501413-pnhi34kohvjln9ikpb0bri6s0mrbqdeb.apps.googleusercontent.com',
    iosClientId: '804262501413-srrmjs2ua5kl0c1ljbe2admm9u2ja8b1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavorfusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYa_d4Yi_5BF9sYlq6DHWzz6TiILNUtko',
    appId: '1:804262501413:web:adaccbed42a31f711fb3cc',
    messagingSenderId: '804262501413',
    projectId: 'flavorfusion-55c75',
    authDomain: 'flavorfusion-55c75.firebaseapp.com',
    storageBucket: 'flavorfusion-55c75.firebasestorage.app',
    measurementId: 'G-B8YRW60NR2',
  );
}
